---
application:
  name: "qovery-app-1-same-router"
  project: "same-router-1"
  organization: "QoveryCommunity"
routers:
- name: "main-qovery-app-1-same-router"
  routes:
  - application_name: "qovery-app-1-same-router"
    paths:
    - "/*"
